# Markdownlint configuration
default: true

# Line length rule
MD013:
  line_length: 88
  code_blocks: false
  tables: false
  headings: false

# Multiple consecutive blank lines
MD012:
  maximum: 2

# Inline HTML
MD033: false

# Emphasis used instead of a heading
MD036: false

# Fenced code blocks should be surrounded by blank lines
MD031: false

# Lists should be surrounded by blank lines
MD032: false

# Bare URL used
MD034: false
