name: Documentation

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "pyevolutionapi/**"
      - "README.md"
      - "mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[docs]"

      - name: Build documentation
        run: |
          if [ -f mkdocs.yml ]; then
            mkdocs build
          else
            echo "No mkdocs.yml found, creating simple redirect"
            mkdir -p site
            cat > site/index.html << 'HTML_END'
          <!DOCTYPE html>
          <html>
          <head>
              <title>PyEvolutionAPI Documentation</title>
              <meta charset="utf-8">
              <meta http-equiv="refresh" content="0; url=https://github.com/lpcoutinho/pyevolutionapi">
              <style>body{font-family:Arial;text-align:center;padding:50px}</style>
          </head>
          <body>
              <h1>PyEvolutionAPI Documentation</h1>
              <p>Redirecting to GitHub repository...</p>
              <p><a href="https://github.com/lpcoutinho/pyevolutionapi">Click here if not redirected</a></p>
          </body>
          </html>
          HTML_END
          fi

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy-pages:
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
